### ISSUE TITLE
貌似不行

### ISSUE THREAD

**Issue by Anikinly** [Jmingzi/vue-slip-delete#1]
一直报错

**Comment by Jmingzi** [comment]
请贴下错误信息

**Comment by Anikinly** [comment]
一直 提示info找不到  我不知道你初始info的类型，我模拟了好几个都报错

**Comment by Jmingzi** [comment]
@Anikinly 什么info？我没有初始化什么东西啊
```vue
<slip-del>
  <p>item</p>
</slip-del>
```
这样用有问题？[demo](https://codepen.io/jmingzi/pen/gzyWGJ)

**Comment by Anikinly** [comment]
再问一句哈  具体删除ui的思路应该是操作dom删除吗 例如this.$el.remove()  还有是比较高端一点的手法

**Comment by Jmingzi** [comment]
@Anikinly 
1. 没有remove方法
2. 你都用vue了还操作dom？
3. v-if
