### ISSUE TITLE
建议可滑动宽度和颜色做成可定制化

### ISSUE THREAD

**Issue by Xue-Felix** [Jmingzi/vue-slip-delete#12]

**Comment by Jmingzi** [comment]
@Xue-Felix 感谢你的建议，这个组件目前提供一种思路，实际场景可能有2个或多个按钮，类似微信左滑。得看业务需求，也可以都做成配置项。但是目前时间不允许。目前颜色是可以通过 props 指定 class 来实现的。如果可以的话你可以自己拷贝这个文件到项目中，无任何依赖。`src/components/SlideDelete.vue`，宽度可以自己修改 data 里的变量即可。

**Comment by Xue-Felix** [comment]
嗯嗯，我现在是这么干的😄
