### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by chanelnumberfive** [Jmingzi/vue-slip-delete#2]
我不太确定自己的见解是不是对的，首先还是特别感谢你造的这个轮子！看你源码的时候，发现你在.m-slide 元素上用addEventListener的方式绑定了三个方法（touchstart touchmove touchend）; 但是当此组件被销毁的时候，是不是应该对应的调用 removeEventListener 来移除绑定的方法，以释放内存？

**Comment by Jmingzi** [comment]
@chanelnumberfive 感谢提醒。页面销毁后，组件只是在domTree中被移除掉了，但vue的vNode是被缓存的（我这里是引用vNode中的el），那对事件的引用也是没有被移除，所以最终不会被销毁。我是发现大厂的组件写的时候也没有手动remove，如果事件直接绑定在元素上， 用`@touchstart`的写法，是否就不用手动移除了？

**Comment by Jmingzi** [comment]
类似和你在组件上绑定Click事件，也是没有手动remove的，所以如果touch事件改写成直接绑定，就不需要remove。。。

**Comment by chanelnumberfive** [comment]
感谢你的回答，现在感觉不用手动移除，我对这块认识也不是特别清楚。。。。。。。。
