### ISSUE TITLE
点击删除按钮之后，状态问题

### ISSUE THREAD

**Issue by andyComeOn** [Jmingzi/vue-slip-delete#4]
如图1
 
![image](https://user-images.githubusercontent.com/19949116/45396793-d7073900-b66f-11e8-832b-87c9794006f8.png)
 共2条数据，若删除第1条数据，我又拉取了一次list接口，但是发现第2条数据的删除按钮是激活的，如图2所示
![image](https://user-images.githubusercontent.com/19949116/45396888-31a09500-b670-11e8-9c05-44c4db532ba0.png)

**Comment by Jmingzi** [comment]
@andyComeOn 你把key值设为数据的id试试

**Comment by andyComeOn** [comment]
试了试可行，我想起了，记得以前有一个帖子讲述的是删除数据用索引有问题，已绑定数据id。3q

**Comment by Jmingzi** [comment]
不是，是因为vue的虚拟dom机制，如果相同的div，key值一样，直接取缓存的vNode了。
