### ISSUE TITLE
删除一个后, 删除按钮 不会关闭

### ISSUE THREAD

**Issue by 857128237** [Jmingzi/vue-slip-delete#5]

**Comment by Jmingzi** [comment]
@857128237 删除后界面不应该更新了么？注意你的key值不要为索引index，设置为数据id

**Comment by 857128237** [comment]
> @857128237 删除后界面不应该更新了么？注意你的key值不要为索引index，设置为数据id

key值是id的, 删除后界面不需要更新, 请问有什么方法吗

**Comment by 857128237** [comment]
> @857128237 删除后界面不应该更新了么？注意你的key值不要为索引index，设置为数据id

还有个问题请教下, 有禁止左滑删除的方法吗, 比如数据列表在拖拽排序的时候, 不允许左滑删除

**Comment by Jmingzi** [comment]
@857128237 因为列表是根据数据渲染的，点击删除后你保持渲染的数据不变就可以。

**Comment by 857128237** [comment]
> @857128237 因为列表是根据数据渲染的，点击删除后你保持渲染的数据不变就可以。

谢谢 再麻烦您看一下禁止的这个问题

**Comment by Jmingzi** [comment]
@857128237 关于禁止，你这个问题我觉得属于业务逻辑了。我提供你一个建议：拖拽排序的时候是另外一个列表，当拖拽完成时才展示这个可以删除的列表。因为是否可拖拽是一个状态控制的。

**Comment by 857128237** [comment]
> @857128237 关于禁止，你这个问题我觉得属于业务逻辑了。我提供你一个建议：拖拽排序的时候是另外一个列表，当拖拽完成时才展示这个可以删除的列表。因为是否可拖拽是一个状态控制的。

我有想过这样写, 但是我这个页面有点复杂,最好能有是否禁止左滑的判断,

**Comment by Jmingzi** [comment]
```html
<div v-if="draggable">
</div>
<slip-del v-else>
</slip-del>
```

没啥成本吧
