### ISSUE TITLE
@author 如果想要和微信那种的有两个按钮 标为未读和删除,有什么建议吗

### ISSUE THREAD

**Issue by 857128237** [Jmingzi/vue-slip-delete#6]

**Comment by Jmingzi** [comment]
@857128237 简单的，我这里是一个，你直接拿源码过去改布局。另外需要注意一个变量，`delAreaWidth: 70;`和`props: threshold: 35;`，同理你改布局宽度后，将dealAreaWidth改为宽度的值，threshold为一半

**Comment by 857128237** [comment]
您好, 我已经改好了,但是我只改了delAreaWidth,没有动threshold的值,有影响吗

**Comment by 857128237** [comment]
源码中 头部  v-slide="" 一直彪红, 是一个警告,有什么方法去除吗

**Comment by Jmingzi** [comment]
是因为指令少了属性，你可以传个`{}`进去

**Comment by Jmingzi** [comment]
threshold的意义是滑动多少，才算打开删除，以至于不会自动关闭掉

**Comment by 857128237** [comment]
都解决了, 谢谢作者

**Comment by Jmingzi** [comment]
谢谢，欢迎多多交流
