### ISSUE TITLE
一个列表里面有两个数组数据,比如我在第一个数组里面左滑了,然后在第二个数组中左滑,第一个数组是不会关闭左滑效果的,请问需要如何调整

### ISSUE THREAD

**Issue by 857128237** [Jmingzi/vue-slip-delete#8]

**Comment by Jmingzi** [comment]
渲染的时候能不能整合成一个呢？能的话最好，如果不能，本身提供了一个方法
```
setOpen(vm) {
  // vm 是当前滑动的实例
  // 你可以在这里手动调用其它实例的setOpen方法去关闭
  // 例如
  this.$refs.list.forEach(vmItem => {
    if (vmItem !== vm) {
      vmItem.setOpen(false)
    }
  })
}
```

**Comment by Jmingzi** [comment]
> 请问下怎么手动关闭那个删除按钮，还有那个setOpen不清楚怎么用，我在上面定义了@setOpen="setopen"，下面在methods里写setopen(vm) {
> console.log(vm);
> }，可什么也不打印

抱歉，现在才回复，你那里写错了，绑定事件：
```js
@slip-open="setopen"
```

**Comment by crydear** [comment]
> > 请问下怎么手动关闭那个删除按钮，还有那个setOpen不清楚怎么用，我在上面定义了@setOpen="setopen"，下面在methods里写setopen(vm) {
> > console.log(vm);
> > }，可什么也不打印
> 
> 抱歉，现在才回复，你那里写错了，绑定事件：
> 
> ```js
> @slip-open="setopen"
> ```

谢谢，不过之前强行用js解决了
